INSERT INTO [user] (name, point) VALUES
(N'Flash Car Group', 0),
(N'Kế Toán Flash Car', 0),
(N'Nguyễn Tiến Đạt - Procar Group', -1.5),
(N'Điều Hành Xe Đức Minh ProCar Group', -1.5),
(N'A A Hải Đăng Travel', 0.75),
(N'A Erick Nguyễn', 6.25),
(N'A Long Travel', 2.25),
(N'A Lử', 0),
(N'A Lử', 0.5),
(N'A Song', 0),
(N'A Tọc Suống Lúi', 7),
(N'Airport Car And Travel', -0.25),
(N'Airport City -- Tổng Đài Blue', 0),
(N'Airport City -- Tổng Đài Red', 1.75),
(N'Airport Lh', 5),
(N'Airport Vehicle Operating', -0.25),
(N'Aloxenoibai', 0.25),
(N'An', 0),
(N'An Đông', 0),
(N'Anh Dũng 2', 0.25),
(N'Ánh Dương', -0.25),
(N'Anh Giap', 0.5),
(N'Anh Hiệp', 0),
(N'Anh Minh', 0),
(N'Ánh Nguyệt', 0.25),
(N'Anh Quân', -0.75),
(N'Anh Sinh', 1),
(N'Anh Thạch', 0.5),
(N'Anh Thái', -0.25),
(N'Anh Tú Airport', 2),
(N'Anh Tuấn 1', 0),
(N'Anh Tuấn 2', 0),
(N'Anh Tuấn 2', 0),
(N'Anliberty', 1.5),
(N'Awaylogs', 0),
(N'B Transport', 0),
(N'Ba Duy', 0.5),
(N'Bảo An Ntl', -0.25),
(N'Bắc Hưng Hải', 0),
(N'Bắc Luận Travel', 0),
(N'Bằng Hip', 0.5),
(N'Bin', -0.75),
(N'Bin Xe Sân Bay', 0),
(N'Bình An One', 0.75),
(N'Bình Minh Khai Innova', -0.25),
(N'Bình Minh Noibaicar', -0.5),
(N'Bom Bi', 0.5),
(N'Bossbuiss', 1.25),
(N'Bốn Long Biên', 0.5),
(N'Bùi Nam Airport', 0),
(N'Cảnh Sát Pro Car', 0),
(N'Car Nội Bài', 0.75),
(N'Chiến Lùn', 0),
(N'Chinh Xe Airport', 4),
(N'Chíp Nguyễn Iphone Zin - Chất', 2.5),
(N'Chu Anh', 0.5),
(N'Chu Lai Time', -0.25),
(N'Chung Láng', 2),
(N'Chung Mậm', 0),
(N'Chung Phạm', 0),
(N'Click Gooo', 0),
(N'Coicity', 1.5),
(N'Công Sơn', -0.25),
(N'Cris Phạm', 0),
(N'Cty Tnhh Du Lịch Bảo An', 17),
(N'Cty Tnhh Mtv Hưng Thịnh Group Travel', 0.25),
(N'Cu Boo Taxi', 0),
(N'Cường Coca', 1.75),
(N'Cường House', 0.75),
(N'Cường Nội Bài', -0.25),
(N'Dịch Vụ Xe Sân Bay', 0.25),
(N'Diệp Diệp', 0.5),
(N'Dinh Van Sac', 0.5),
(N'Do Chien', -0.25),
(N'Do Van Anh', 0),
(N'Do Xuan Ha', 0),
(N'Dominic Tuấn Linh', 1),
(N'Dovannd', -0.5),
(N'Dragon', -0.5),
(N'Duc Anh', 2.25),
(N'Duc Travel', 0),
(N'Dũng Béoo', 1),
(N'Dung Duong', 0.25),
(N'Dũng Điều Hành Xe', 0.75),
(N'Dũng Hân Travel', 0),
(N'Dũng Nội Bài Airport', 0.75),
(N'Dũng Tóc Dài', 0),
(N'Duong Bob', 4.5),
(N'Duytuân', 0),
(N'Dương Khánh', 0.25),
(N'Dương Thành Chung', 0),
(N'Dương Văn Giáp', 1),
(N'Dv - Xe Gia Đình', 0),
(N'Dvu Xe Sân Bay Và Đường Dài', 0),
(N'Đào Huy', 0),
(N'Đào Thành Đồng', 0.5),
(N'Đăng Công', 0),
(N'Đặng Đạt 1', -0.25),
(N'Đặng Đạt 2', 0),
(N'Đặng Thành Trang Vios', 0),
(N'Đặng Văn Trung', 0.75),
(N'Đặt Xe Gọi 0971051056', 0),
(N'ĐH xe dịch vụ Anh Duy', 0),
(N'Đièu Hành Xe Nội Bai', 7.75),
(N'Điều Hành PHCAR Airport', 0),
(N'Điều Hành Xe Flash', 0),
(N'Điều Hành Xe Huy Hoàng Travel', 4.5),
(N'Điều Hành Xe Open', 2.5),
(N'Điều Xe Nội Bài Pro', 0),
(N'Đình Kiên', 0.25),
(N'Đinh Quang Dũng', 0),
(N'Đoàn Hoàng Duy', 0),
(N'Đoàn Tiến', 0.5),
(N'Đoàn Văn Tuyên', -0.25),
(N'Đón Trả Khách Hà Nội', 0),
(N'Đỗ Bách', 2.75),
(N'Đỗ Long', 0),
(N'Đỗ Mạnh Hoạ', 0),
(N'Đỗ Ngọc Anh', 2),
(N'Đỗ Ngọc Đông', 0),
(N'Đỗ Nhật Đức', 0),
(N'Đỗ Thành Trung', 0),
(N'Đỗ Tuấn Nam', 0),
(N'Đỗ Tuấn Nghĩa', 1),
(N'Đỗ Xuân Hưng', 0),
(N'Đức 1', 1),
(N'Đức 2', -0.25),
(N'Đức Anh Tx', 1.25),
(N'Đức Âm', 0),
(N'Đức Cảnh 1', 1.25),
(N'Đức Huyền', 1.75),
(N'Đức Logistics', 1),
(N'Đức Nguyễn', 0),
(N'Đức Thịnh 2', -0.75),
(N'Đức Xesanbaycarcom', 1.5),
(N'E Car', 0),
(N'Gã Đầu Trọc', -0.5),
(N'Giang Lêu', 3),
(N'Gió Travel', 0),
(N'Gọi Xe Là Có', 4.25),
(N'Gỗ', 5.75),
(N'H-m Nội Bài Airport', 5),
(N'Hà Hóm Hỉnh', 1),
(N'Ha Mario', 0),
(N'Ha Noi Open Tours', 1),
(N'Hải Đăng Travel', 0),
(N'Hái Hoa Tặc', 3),
(N'Hạnh Phúc Vui Vẻ', 0),
(N'Hanhxd1', 0),
(N'Hân Hân', 2),
(N'Hg Rent A Car', 1.5),
(N'Hiền Vũ', 0),
(N'Hiệp Vũ Car', 0),
(N'Hiếu Láng', 0),
(N'Hitman', 6.5),
(N'Hn Travel', 5.75),
(N'Ho Dinh Huy', 1),
(N'Hoa', 0),
(N'Hoa Hoa', 3.5),
(N'Hòa Trần Procar Group', 0.25),
(N'Hoài Nam Sapa', 0),
(N'Hoàn Đx', 0),
(N'Hoàng', 0.5),
(N'Hoàng Anh 1', 1.25),
(N'Hoàng Anh Dk Car', 0.25),
(N'Hoàng Ba', 0.25),
(N'Hoang Bạch Mai', 2.25),
(N'Hoàng Dân', -0.25),
(N'Hoàng Hải Airport', 0.5),
(N'Hoang Huy 1', 0.5),
(N'Hoàng Lâm Airport', 0),
(N'Hoang Minh Transport', 0),
(N'Hoàng Nt', 0),
(N'Hoàng Phi Hồng', -0.25),
(N'Hoàng Sáng 1', 0),
(N'Hoàng Thắng', -0.25),
(N'Hoàng Thiên', 0),
(N'Hoàng Trung Thông', 0.5),
(N'Hoàng Xuân Phú', 1),
(N'Hoat', 0),
(N'Hồ Kiên', 0.5),
(N'Hồ Phi Tiến', -0.25),
(N'Hồ Thị Hớn Hở', 0),
(N'Huân Ngọc', -0.25),
(N'Hùng', 0.5),
(N'Hung Airport', 0),
(N'Hùng Airport Vip', 1.5),
(N'Hùng Fortuner', 0.25),
(N'Huong Nghi', -0.5),
(N'Huong Nguyenvan', 2.75),
(N'Huy', 0),
(N'HuY', 0.25),
(N'Huy Binh', 0),
(N'Huy Đinh', -0.25),
(N'Huy Khánh', 0),
(N'Huy Nguyễn', 0),
(N'Huy Tây Hồ', 0),
(N'Huyen', -0.25),
(N'Huyenthangtravel', 0),
(N'Hưng', 0),
(N'Hường', 0),
(N'Hương Minh Anh', 0),
(N'Hữu Điệp', -0.25),
(N'Jonh Đường', 0.5),
(N'Kaka Phi', 0),
(N'Kant Do', 0.5),
(N'Karseell Macca Thắng', 0),
(N'Kelvin Tran', -0.25),
(N'Kensutom Transport', 0),
(N'Kế Toán Xe Gia Đình', 0.5),
(N'Khánh Cerato', 0),
(N'Khánh Đoàn', -0.25),
(N'Khánh Ly Nội Bài', 0),
(N'Khánh Toàn', 1.5),
(N'Khiem Nguyen', 0),
(N'Khoa Lê', 2.5),
(N'Khuyen Mau', -0.25),
(N'Kiennoibai', 0),
(N'Kiếm Anh', 0),
(N'Kiên Đt', 2),
(N'Kiên Trang Vũ', 0),
(N'Kiênt City', 0.75),
(N'Kiều Anh Tuấn', 4),
(N'Kiều Trung', 0),
(N'Kim', 22.75),
(N'Kin', 0.5),
(N'Ks Car Pro', 0),
(N'Lamlam', 1.75),
(N'Lap Accent', 0.5),
(N'Le Bao', 2.5),
(N'Lequang', 0),
(N'Levietduc', 0),
(N'Lê Diện', -0.25),
(N'Lê Hải', 2),
(N'Lê Hoan', 0),
(N'Lê Hồng Nguyên', -1),
(N'Lê Hùng Dũng', 0),
(N'Lê Mạnh Hà', -0.5),
(N'Lê Sỹ Thành', 0.25),
(N'Lê Văn Thắng', 0),
(N'Liêm Bùi', 0.5),
(N'Lin Tin', 0.75),
(N'Linkcar', 0),
(N'Long Hiệp', 0),
(N'Long Lê', 0.75),
(N'Lợi Xe Bò', 0.25),
(N'Luan Mazda', 3),
(N'Luân Crt', 0),
(N'Luu Quang Dat', 0),
(N'Luxury Car Airport', 11),
(N'Luyện Nguyễn Tb', 0.5),
(N'Lương Anh Tài Airport', -0.5),
(N'Lương Văn Duy', 0),
(N'Lưu Tiến Hoàng', 0),
(N'Lưusretno', 0),
(N'Mạc Văn Túy', -0.25),
(N'Mai Lâm', 0.5),
(N'Mai Linh', 1.25),
(N'MANH', 0),
(N'Mạnh Hd Airport', 0),
(N'Mạnh Hùng Duy', 0),
(N'Mạnh Pháo Jr', -0.25),
(N'Manh Tan', 1.25),
(N'May - Travel', 0),
(N'Meo', 0),
(N'Minh Chi', -0.25),
(N'Minh Đông', 0),
(N'Minh Hồ', 0),
(N'Minh Quang Xe Sân Bay', 0.25),
(N'Minh Quân', 0),
(N'Minh Thắng', 0),
(N'Minh Trí Travel', 4.25),
(N'Miu Miu', 0),
(N'Mr Dân', 0.25),
(N'Mr Đàm', 0.5),
(N'Mr Đức Đạt', 0),
(N'Mr Long', 3),
(N'Mr Sỹ', 0),
(N'Mr Tú', 0.5),
(N'Mr Xevip', 3),
(N'Nam Khánh', 0),
(N'Nam Le ph', 1.25),
(N'Nam Tô', 0),
(N'New World', 0.5),
(N'Ngây Ngô', 0),
(N'Nghĩa Nguyễn', 0),
(N'Nghiêm Huy Biên', 0),
(N'Ngọc Anh Phạm', -0.25),
(N'Ngọc Châm', 0.75),
(N'Ngọc Đồng', 2),
(N'Ngọc Huynh', 0.25),
(N'Ngọc Hướng', 0),
(N'Ngoc Phung Xpander', 0),
(N'Ngoczen', 1),
(N'Nguyen Duc', 2.25),
(N'Nguyen Hoang Sang', 0),
(N'Nguyen Quy Tuyen', 2.25),
(N'Nguyen Son', 0),
(N'Nguyen Thanh Tung', 0.5),
(N'Nguyen Thuan', 0),
(N'Nguyen Tien Dat', 1),
(N'Nguyen Van Chien', 0),
(N'Nguyendam', 0),
(N'Nguyenvantho', -0.25),
(N'Nguyenvu', 0),
(N'Ng脸上 Bảo Trung', 0.5),
(N'Nguyễn Cao Nguyên', -0.25),
(N'Nguyễn Đình Thức', 0),
(N'Nguyễn Đức Nam', 0),
(N'Nguyễn Hoàn', 1.5),
(N'Nguyễn Hoàng HD', 0),
(N'Nguyễn Hương', 0),
(N'Nguyễn Hữu Việt', 1),
(N'Nguyên Khac Quyêt', 0.75),
(N'Nguyễn Mạnh Cưòng 1', 0),
(N'Nguyễn Mạnh Toàn', -0.75),
(N'Nguyễn Minh', 0),
(N'Nguyễn Minh Hoàng', 0),
(N'Nguyễn Minh Tính', 0),
(N'Nguyễn Quang Ngọc', 2.5),
(N'Nguyễn Quang Thiện', 7.75),
(N'Nguyễn Quý Linh', -0.25),
(N'Nguyễn Sĩ', 0.25),
(N'Nguyên Sorento', 0),
(N'Nguyễn Thanh', 0),
(N'Nguyễn Thành', 0),
(N'Nguyễn Thanh Hoa', 0),
(N'Nguyễn Thành Trung', 4),
(N'Nguyễn Thùy Xe Sân Bay', 5.25),
(N'Nguyễn Trần Quang', 1.75),
(N'Nguyễn Trọng Quý', 0),
(N'Nguyễn Tùng Ca', 7),
(N'Nguyễn Văn Minh', 4.25),
(N'Nguyễn Văn Mỹ', 1.5),
(N'Nguyễn Văn Quân Bảo', 0.5),
(N'Nguyễn Văn Thoại', -0.25),
(N'Nguyễn Việt Cường Airport', 0),
(N'Nguyễn Vinh - Nhà Xe Bình An', 0.5),
(N'Nguyên Xe Sân Bay', 1.25),
(N'Nguyễn Xuân Du', 1),
(N'Nguyễn Xuân Vệ', 0),
(N'Nguyệt Bảo Minh', 20),
(N'Nguyệt Xe Nội Bài', 3.5),
(N'Người Bản Địa Tranporter', 0),
(N'Ngvanthom', 0),
(N'Nhà Đẹp Nhà Thép Đẹp', 3.5),
(N'Nhà Xe Hồng Phát', 0),
(N'Nhà Xe Hùng Phương', 0.25),
(N'Nhà Xe Huỳnh Phương', 0.75),
(N'Nhà Xe Kỳ Anh', 0),
(N'Nhà Xe Linh An', 0),
(N'Nhà Xe Thành Công', 6),
(N'Nhà Xe Tùng Lâm', 3.5),
(N'Nhà Xe Việt Phương', 3.25),
(N'Nhân', 0.5),
(N'Nhật Tưởng', 0.5),
(N'Như Hải', 2.5),
(N'Nink', 0),
(N'Noibaitransport', 0),
(N'Nội Bài Bảo Khánh', -0.25),
(N'Nội Bài Dịch Vụ', 0.75),
(N'Nội Bài Hoàng Gia', -0.25),
(N'Operating', 0.5),
(N'Optical Airport', 13),
(N'Phạm Công Thắng', 0),
(N'Phạm Duy Airport', 1),
(N'Phạm Đức Vũ', 0),
(N'Phạm Ngọc Thể', 0),
(N'Phạm Quốc Việt', 10.75),
(N'Pham Thanh Hieu', 0),
(N'Phạm Văn Thẩm cọc 2d', 0),
(N'Pham Xuan Viet', 0),
(N'Phamdat', 0),
(N'Phamhieu9999', 0),
(N'Phan Đức Cường', 3.75),
(N'Phan Long Biên', -0.25),
(N'Phan Tuấn', 0),
(N'Phátnq', -1),
(N'Phí Hoài Anh', 0.5),
(N'Phong China', 1.25),
(N'Phong mazdaz', 1.5),
(N'Phúc', 1),
(N'Phương Phương', -0.25),
(N'Putin', 0.5),
(N'Q D', 0),
(N'Quách Minh', 0),
(N'Quang Anh', 0),
(N'Quang Chiến Đinh', 0),
(N'Quang Đạt Travel', 0.5),
(N'Quang Lốp Xe Sân Bay', 1.25),
(N'Quannguyen', 1.75),
(N'Quân Quân', 0),
(N'Quốc Cường', 0.5),
(N'Quýbéo Smile Noibaiairport', 0),
(N'Quyết Mda', -0.25),
(N'Quyết Sân Bay', 4),
(N'Rambo', 1.75),
(N'Sabo Tên Lửa', 3),
(N'Sao Mai', 0),
(N'Sân Bay Và Đi Tỉnh', 0),
(N'Scar Xe Sân Bay Và Đi Tỉnh', 0.5),
(N'Sontran', 0.5),
(N'Stinkerman', 0.5),
(N'Susu Sb', -0.5),
(N'T Quang Minh', 0),
(N'Tạ Đức Anh', 3.25),
(N'Tạ Huê', 0),
(N'Tạ Ngọc Linh', 0),
(N'Tạ Ngọc Tuyên', 0),
(N'Tạ Xuân Nhất', 0.25),
(N'Taxi Anh Khương', -0.75),
(N'Taxi Bình An', -0.25),
(N'Taxi Gia Đình - Tây Nguyễn', 0),
(N'Taxi Hà Nội', 0),
(N'Taxi Noibai Chính Hãng', 0.25),
(N'Taxi Nội Bài Tiến Dũng - Xe Đi Các Tỉnh', 4.25),
(N'Taxi Nội Bài Và Du Lịch', 0),
(N'Taxi Nội Bài Và Đi Các Tỉnh', 0),
(N'Taxi Sân Bay 1', 3.75),
(N'Taxi Sân Bay Nội Bài', 0.25),
(N'Taxi Thạch Thất', 0),
(N'Tăng Bảo Châu', 0.25),
(N'Tâm Sb', 0),
(N'Tân', 0.5),
(N'Tân Lê', 1),
(N'Thang Van', -1),
(N'Thanh Bình', 0),
(N'Thành Chung', 2),
(N'Thành Dũng', 1.25),
(N'Thành Fortuner', 0),
(N'Thanh Lâm', 0.25),
(N'Thanh Sơn Travel', 0),
(N'Thanh Tùng Airport', 0),
(N'Thanh Vân', 0),
(N'Thanh Vinh', 0.25),
(N'Thành Vũ', 0),
(N'Thắng 2', 0),
(N'Thắng Còi', 0),
(N'Thắng Innova', 1.5),
(N'Thắng Mabu', -0.25),
(N'Thắng Tây', 1.25),
(N'The Flash', 0),
(N'The Light', 0),
(N'The Lucky One', 0),
(N'Thế Anh 1', 0),
(N'Thế Hòa Lạc', 0),
(N'Thị Na', 1.5),
(N'Thợ Săn Thành Phố', 3.25),
(N'Thu Đinh', 0.5),
(N'Thu Hoàng', 9),
(N'Thu Xe Bt', 3),
(N'Thuan Le', 0),
(N'Thuấn Xe Ghép', 0),
(N'Thuy Hang', 4.75),
(N'Thủy Tiên Xe Du Lịch', 0),
(N'Thưởng Cao', -0.25),
(N'Tiendatvan', 0),
(N'Tienlevan', 0),
(N'Tiền Cerato', 0.5),
(N'Tiến Gl', 0),
(N'Tiến Hoà', 0.25),
(N'Tiến Taxi', 0.5),
(N'Tiến Trần Đức', 2.25),
(N'Tin Nguyễn', 2.75),
(N'Toni Trần', -0.25),
(N'Tonny Trần', -0.25),
(N'Tony Đức', 0),
(N'Tô Thế Minh', 0),
(N'Tổng Đài Sân Bay', 2.5),
(N'Tổng Đài Taxi Sân Bay Đi Tỉnh', 0.25),
(N'Tổng Đài Xe Ghép Hạ Hoà Hà Nội', 2.25),
(N'Tới Bến', -0.25),
(N'Traihen', 0),
(N'Tran Cuong', 0.5),
(N'Tran Xuan Bich', -1.5),
(N'Trananhtu', -0.25),
(N'Trang Anh', 0),
(N'Tranminhhd', 0),
(N'Tranndai', 0.5),
(N'Trần Chí Hiếu', 0),
(N'Trần Hậu', 0),
(N'Trần Hòa', 0),
(N'Trần Hoàng Minh', 0),
(N'Trần Hoàng Thiện', 4),
(N'Trần Huyện', 0),
(N'Trần Ngọc Anh', 0.75),
(N'Trần Quốc Khánh', 2),
(N'Trần Trung', 5.25),
(N'Trần Tuấn Minh', -0.25),
(N'Trần Văn Doanh', -0.25),
(N'Trình Nguyễn', 0),
(N'Trình Văn Hoàng', 0),
(N'Trọng Lâm', 0),
(N'Trọng Madza', 0),
(N'Trọngnt Pờ Rồ', 0.5),
(N'Trùm Bia Hơi Phương Nam', 0),
(N'Trung City', 4.5),
(N'Trung Hiếu Nội Bài', 0.5),
(N'Trung Kều', 0.75),
(N'Trung Nguyen', 6.5),
(N'Trung Péo Pro', 1.5),
(N'Trung Vios', 0.75),
(N'Trường An', 1.5),
(N'Trường Key Trần', -0.25),
(N'Trương Toàn', 0.25),
(N'Trườngquang', 0.25),
(N'Tú Hoàng Tú Sữa', 0),
(N'Tú Nguyễn', 0),
(N'Tú Phạm', 0.5),
(N'Tú Tây Sơn', 0),
(N'Tú Xe Ôm', 0.5),
(N'Tú Xe Sân Bay Và Đường Dài', -0.25),
(N'Tuan Anh Nội Bài', 0),
(N'Tuan Le Innova', 0.5),
(N'Tuan Pham Long', 2.5),
(N'Tuankt', 0),
(N'Tuantt', 0),
(N'Tuấn 2 599', 7.5),
(N'Tuấn Accent', 0),
(N'Tuấn Anh 1', -0.5),
(N'Tuấn Anh 5', 0),
(N'Tuấn Anh 5', 0.5),
(N'Tuấn Anh Aat', 0),
(N'Tuấn Anh Airport', 0),
(N'Tuấn Anh Nb', 0.25),
(N'Tuấn Anh Nội Bài', 1.5),
(N'Tuấn Anhh', 0),
(N'Tuấn Ba', -0.25),
(N'Tuấn Dương 1', 0),
(N'Tuấn Kiệt', 0),
(N'Tuấn Lee', 0),
(N'Tuấn Lùi Giấu Biển', 0.25),
(N'Tuấn Ncd', -0.25),
(N'Tuấn Nguyễn', 0),
(N'Tuấn Sedona - Carnival Hn', 0.5),
(N'Tuấn Siu', -0.25),
(N'Tuấn Taxi', 0),
(N'Tuấn Trung', 1.5),
(N'Tuấn Tú', 0),
(N'Tùng Travel', 3.5),
(N'Týt Tồ', 0.25),
(N'Uông A Tùng', 0),
(N'Út Tân', 0.25),
(N'Vanhoa Nội Bài', 0.5),
(N'Văn Anh', 0),
(N'Văn Chức', 0.5),
(N'Văn Dũng', 0),
(N'Văn Hảo Anh', 0),
(N'Văn Hùng', 0),
(N'Văn Phòng Golden Car Hn', -2),
(N'Văn Tuân', 1),
(N'Vân Khánh', 0),
(N'Vận Tải Cao Sơn', 0.5),
(N'Vận Tải Du Lịch Hoàng Cường', 0.25),
(N'Vận Tải Hà Phương', -0.25),
(N'Vận Tải Hoàng Nam', 0),
(N'Vận Tải Ngọc Hải', 0.25),
(N'Vận Tải Tuấn Long', -0.25),
(N'Vi', 0),
(N'Vietgo xe sân bay giá rẻ', 10.5),
(N'Việt Anh', 0),
(N'Việt Yên Travel', -0.5),
(N'Vinh Black', 0.5),
(N'Vinh Đại Ca Nguyễn Ngọc Vinh', 0),
(N'Vinh Le', 0),
(N'Vinhomes Airport', 0),
(N'Visnam', -0.75),
(N'Vp Du Lịch Bình Minh', 0),
(N'Vp Xe Du Lịch Hà Nội', 0),
(N'VU', 0),
(N'Vũ', 0),
(N'Vũ Cao Sang', 0),
(N'Vũ Công Hiếu', -0.25),
(N'Vũ Duy Chính', 0.75),
(N'Vũ Dương', 0.25),
(N'Vũ Gia', 0.25),
(N'Vũ Hoàng Long', 0),
(N'Vũ Nghĩa', 3.75),
(N'Vũ Quang Bình', 0),
(N'Vũ Thanh', 0),
(N'Vu Tuan Phương', 0),
(N'Vũ Tuấn', 0.25),
(N'Vuong Ngoc', 0),
(N'Vượng Fortuner', 0),
(N'Wta', 0.5),
(N'Xe Bay Nội Bài', 0.5),
(N'Xe Buýt Nội Bài', 0),
(N'Xe Du Lịch Hà Thành', 0.25),
(N'Xe Du Lịch Thành Công', 0),
(N'Xe Dv Đức Dương', 2.75),
(N'Xe Gia Đình Gia Huy', 0),
(N'Xe Ngọc Bảo', 0.75),
(N'Xe Nội Bài', 0),
(N'Xe Nội Bài Minh Vũ', 0),
(N'Xe Nội Bài Qm', 0.25),
(N'Xe Nội Bài Sạch', 0.5),
(N'Xe Sân Bay Đạt Loan', 0),
(N'Xe Sân Bay Đi Tỉnh - Bảo Linh Car', -0.25),
(N'Xe Sân Bay Tour Tỉnh', 0),
(N'Xe Sân Bay Và Đi Tỉnh Dv', 0.25),
(N'Xe Sân Bay Và Đường Dài', 3),
(N'Xe Tiện Chuyến - Davids Vũ', 0),
(N'Xe Vip Hn Nb', 0),
(N'Xebảychỗxpander', 0),
(N'XedulichVietnam', 0.5),
(N'Xesanbaygiare Vn', 0),
(N'Xevipnoibaivn', 7.25),
(N'Xuân Nguyễn', 0),
(N'Xuân Thao_Airport', 0.5),
(N'Xuân Thiện', 0),
(N'Xuân Thịnh', 0),
(N'Zcar', 0),
(N'Nguyễn Quân', 0.25),
(N'Quang Hải', -0.25),
(N'Lê Quang Đạo', 0),
(N'Quang Thịnh', 0.25);